run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
